<?php

namespace App\Model;

use Illuminate\Database\Eloquent\Model;

class WechatUser extends Model
{
    protected $table = 'wechat_user';
    protected $fillable = ['name', 'email','avatar_url'];

    protected static function boot()
    {
        parent::boot(); // TODO: Change the autogenerated stub
        static::creating(function ($model) {
            if (!$model->unique_id) {
                $model->unique_id = static::getUniqueNo();
            }
        });
    }

    static public function getUniqueNo()
    {
        do {
            //生成9位的唯一id号
            $unique = mt_rand(100000000, 9999999999);
        } while (self::query()->where('unique_id', $unique)->exists());

        return $unique;
    }

    public function louJie()
    {
        return $this->hasMany(Lou::class, 'creditors_user_id', 'id');
    }

    public function louQian()
    {
        return $this->hasMany(Lou::class, 'debts_user_id', 'id');
    }

    public function messages()
    {
        return $this->hasMany(Message::class, 'user_id', 'id');
    }

    public function record()
    {
        return $this->hasMany(UserRecord::class, 'user_id', 'id');
    }
}
